### ISSUE TITLE
MGLPointAnnotations flicker after being added to the map

### ISSUE THREAD

**Issue by Jackhammer42** [mapbox/mapbox-gl-native-ios#273]
Hi, i am seeing an issue in iOS where annotations flicker once after being added to the map.

I am using the `mapView.addAnnotations` method to add an Array of `MGLPointAnnotation` to my instance of the `MGLMapView`. It seems like the described behavior was introduced in version 5.5.0. I do not see this in prior versions.

### Configuration

**Mapbox SDK versions:** 5.5.0 to 6.0.0
**iOS/macOS versions:** iOS 13
**Device/simulator models:** iPhone XS
**Xcode version:** 11

**Comment by julianrex** [comment]
@pozdnyakov can you confirm this should have been fixed in 6.0.0? Looks like the OP was updated to include 6.0.0 too.

**Comment by pozdnyakov** [comment]
@julianrex it was partially fixed for this version (shall be mitigated for the maps without ongoing animations), work on the complete solution is in progress.

**Comment by knov** [comment]
@Jackhammer42 We've made an improvement in the rendering that we believe resolves this issue in iOS < 14. Can you try picking up our latest release - [v6.1.0](https://github.com/mapbox/mapbox-gl-native-ios/releases/tag/ios-v6.1.0)

**Comment by knov** [comment]
@Jackhammer42 I've tested with the example project you posted [here](https://github.com/mapbox/mapbox-gl-native/issues/16473#issuecomment-665527188 ) and am not able to replicate this flickering.

**Comment by Jackhammer42** [comment]
@knov Yes, as far as I can tell the issue is gone! Thank you very much.
