### ISSUE TITLE
Xcode 12 dylib error

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-gl-native-ios#487]
# Steps to reproduce

 1. Use Xcode 12.0 or later
 2. install Mapbox SDK v6.2.1 using CocoaPods
 3. build the app

### Expected behavior

No errors

### Actual behavior
Can't build this is the error preventing it:
`building for iOS, but linking in dylib file (/Users/marcocarnevali/Library/Developer/Xcode/DerivedData/<AppName>-ackcfwuxqhtmbgcrnvtojbpyrrnk/Build/Products/Release-iphoneos/MapboxCommon.framework/MapboxCommon) built for iOS Simulator, file '/Users/marcocarnevali/Library/Developer/Xcode/DerivedData/<AppName>-ackcfwuxqhtmbgcrnvtojbpyrrnk/Build/Products/Release-iphoneos/MapboxCommon.framework/MapboxCommon' for architecture arm64`

### Configuration

**Mapbox SDK versions: 6.2.1** 
**iOS versions: 14.0 ** 
**Device/simulator models: every iPhones**
**Xcode version: 12.0**

**Comment by captainbarbosa** [comment]
Hi @MarcoCarnevali - I think this will be addressed by https://github.com/mapbox/mapbox-gl-native-ios/pull/482.

In the meantime, if you could provide the exact version of CocoaPods and Xcode you're using that would be helpful. Thanks!

**Comment by MarcoCarnevali** [comment]
@captainbarbosa my CocoaPods version is: v1.9.3 while Xcode is version 12.0.
My problem seems to be quite the opposite. Excluding arm64 let me build for the simulator but I still can't build for my devices either with arm64 excluded or not.

**Comment by ZiZasaurus** [comment]
@MarcoCarnevali, if you set the build settings to `Any iOS simulator` instead of `Any SDK` it should allow you to also build to devices. I ran across a similar issue when testing. 

<img width="514" alt="Screen Shot 2020-09-29 at 6 33 07 PM" src="https://user-images.githubusercontent.com/44972592/94623455-1742af80-0269-11eb-97f2-65dafadda8a4.png">

**Comment by MarcoCarnevali** [comment]
@ZiZasaurus this is what I have but I still can't build for the device
<img width="878" alt="Schermata 2020-09-30 alle 14 37 51" src="https://user-images.githubusercontent.com/9656572/94686047-88966700-032a-11eb-98c1-d63985b20112.png">

**Comment by MarcoCarnevali** [comment]
I fixed it following this: https://github.com/mapbox/mapbox-navigation-ios/issues/2674

**Comment by DusanEastcode** [comment]
hello everyone, can you please fix the settings here in these examples? https://github.com/mapbox/navigation-ios-examples settings (excluded architectures) mentioned here doesn't work for me.

**Comment by noway** [comment]
Can this please be reopened? This still happens on Apple Silicon M1

**Comment by ManthanSutariya** [comment]
still facing this issue on mac m1

**Comment by korczis** [comment]
Same here

**Comment by felix-ht** [comment]
getting the same issue but only building for the simulator

**Comment by felix-ht** [comment]
adding  this to the podfile fixed this for me in flutter on an m1 mac

```ruby
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

**Comment by sharon-atim** [comment]
Add this to the Podfile.

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

**Comment by sryze** [comment]
How is adding arm64 to EXCLUDED_ARCHS a solution? It forces the app to be compiled for x86_64 instead of ARM64 and the simulator runs through Rosetta as a result. This is not efficient.
